export interface SkillDefinition {
  name: string;
  category: string;
}

export const SKILL_CATEGORIES = [
  "Leadership & Management",
  "Marketing & GTM",
  "Product & Design",
  "Engineering & Technical",
  "Finance & Operations",
  "Data & Analytics",
  "Creative",
  "Other",
] as const;

export const SKILLS_LIBRARY: SkillDefinition[] = [
  // ─── Leadership & Management (55) ───────────────────────────────────
  { name: "Team Management", category: "Leadership & Management" },
  { name: "Hiring", category: "Leadership & Management" },
  { name: "Performance Management", category: "Leadership & Management" },
  { name: "Organizational Design", category: "Leadership & Management" },
  { name: "Executive Communication", category: "Leadership & Management" },
  { name: "Board Relations", category: "Leadership & Management" },
  { name: "Culture Building", category: "Leadership & Management" },
  { name: "Change Management", category: "Leadership & Management" },
  { name: "Coaching", category: "Leadership & Management" },
  { name: "Mentorship", category: "Leadership & Management" },
  { name: "Strategic Planning", category: "Leadership & Management" },
  { name: "Cross-Functional Leadership", category: "Leadership & Management" },
  { name: "Stakeholder Management", category: "Leadership & Management" },
  { name: "Conflict Resolution", category: "Leadership & Management" },
  { name: "Executive Presence", category: "Leadership & Management" },
  { name: "Talent Development", category: "Leadership & Management" },
  { name: "Succession Planning", category: "Leadership & Management" },
  { name: "Remote Team Management", category: "Leadership & Management" },
  { name: "Diversity & Inclusion", category: "Leadership & Management" },
  { name: "Team Building", category: "Leadership & Management" },
  { name: "OKR Setting", category: "Leadership & Management" },
  { name: "KPI Development", category: "Leadership & Management" },
  { name: "Decision Making", category: "Leadership & Management" },
  { name: "Delegation", category: "Leadership & Management" },
  { name: "Investor Relations", category: "Leadership & Management" },
  { name: "Crisis Management", category: "Leadership & Management" },
  { name: "Negotiation", category: "Leadership & Management" },
  { name: "Public Speaking", category: "Leadership & Management" },
  { name: "Meeting Facilitation", category: "Leadership & Management" },
  { name: "Employee Engagement", category: "Leadership & Management" },
  { name: "Retention Strategy", category: "Leadership & Management" },
  { name: "Employer Branding", category: "Leadership & Management" },
  { name: "M&A Integration", category: "Leadership & Management" },
  { name: "Scaling Organizations", category: "Leadership & Management" },
  { name: "Executive Hiring", category: "Leadership & Management" },
  { name: "Board Reporting", category: "Leadership & Management" },
  { name: "Company Values Design", category: "Leadership & Management" },
  { name: "Leadership Development", category: "Leadership & Management" },
  { name: "360 Feedback", category: "Leadership & Management" },
  { name: "Compensation Design", category: "Leadership & Management" },
  { name: "Equity Planning", category: "Leadership & Management" },
  { name: "Organizational Health", category: "Leadership & Management" },
  { name: "Offsite Planning", category: "Leadership & Management" },
  { name: "Internal Communications", category: "Leadership & Management" },
  { name: "Vision Setting", category: "Leadership & Management" },
  { name: "Mission Development", category: "Leadership & Management" },
  { name: "People Operations", category: "Leadership & Management" },
  { name: "Headcount Planning", category: "Leadership & Management" },
  { name: "Onboarding Design", category: "Leadership & Management" },
  { name: "Influence Without Authority", category: "Leadership & Management" },
  { name: "Executive Coaching", category: "Leadership & Management" },
  { name: "Upward Management", category: "Leadership & Management" },
  { name: "Feedback Culture", category: "Leadership & Management" },
  { name: "Workforce Planning", category: "Leadership & Management" },
  { name: "Performance Reviews", category: "Leadership & Management" },

  // ─── Marketing & GTM (55) ───────────────────────────────────────────
  { name: "Brand Strategy", category: "Marketing & GTM" },
  { name: "Demand Generation", category: "Marketing & GTM" },
  { name: "Content Marketing", category: "Marketing & GTM" },
  { name: "Product Marketing", category: "Marketing & GTM" },
  { name: "Lifecycle Marketing", category: "Marketing & GTM" },
  { name: "Paid Acquisition", category: "Marketing & GTM" },
  { name: "SEO", category: "Marketing & GTM" },
  { name: "Growth Marketing", category: "Marketing & GTM" },
  { name: "GTM Strategy", category: "Marketing & GTM" },
  { name: "Customer Research", category: "Marketing & GTM" },
  { name: "Positioning", category: "Marketing & GTM" },
  { name: "Messaging", category: "Marketing & GTM" },
  { name: "Email Marketing", category: "Marketing & GTM" },
  { name: "Social Media Marketing", category: "Marketing & GTM" },
  { name: "Influencer Marketing", category: "Marketing & GTM" },
  { name: "Community Building", category: "Marketing & GTM" },
  { name: "PR & Communications", category: "Marketing & GTM" },
  { name: "Event Marketing", category: "Marketing & GTM" },
  { name: "Partner Marketing", category: "Marketing & GTM" },
  { name: "ABM (Account-Based Marketing)", category: "Marketing & GTM" },
  { name: "Marketing Analytics", category: "Marketing & GTM" },
  { name: "Conversion Rate Optimization", category: "Marketing & GTM" },
  { name: "Marketing Automation", category: "Marketing & GTM" },
  { name: "Launch Strategy", category: "Marketing & GTM" },
  { name: "Competitive Analysis", category: "Marketing & GTM" },
  { name: "Market Research", category: "Marketing & GTM" },
  { name: "Audience Segmentation", category: "Marketing & GTM" },
  { name: "Pricing Strategy", category: "Marketing & GTM" },
  { name: "Sales Enablement", category: "Marketing & GTM" },
  { name: "Channel Strategy", category: "Marketing & GTM" },
  { name: "Referral Programs", category: "Marketing & GTM" },
  { name: "Affiliate Marketing", category: "Marketing & GTM" },
  { name: "Brand Positioning", category: "Marketing & GTM" },
  { name: "Customer Acquisition", category: "Marketing & GTM" },
  { name: "Retention Marketing", category: "Marketing & GTM" },
  { name: "Performance Marketing", category: "Marketing & GTM" },
  { name: "SEM / PPC", category: "Marketing & GTM" },
  { name: "Content Strategy", category: "Marketing & GTM" },
  { name: "Thought Leadership", category: "Marketing & GTM" },
  { name: "Webinar Production", category: "Marketing & GTM" },
  { name: "Case Study Development", category: "Marketing & GTM" },
  { name: "Customer Advocacy", category: "Marketing & GTM" },
  { name: "Marketing Operations", category: "Marketing & GTM" },
  { name: "Lead Scoring", category: "Marketing & GTM" },
  { name: "Funnel Optimization", category: "Marketing & GTM" },
  { name: "Campaign Management", category: "Marketing & GTM" },
  { name: "PLG (Product-Led Growth)", category: "Marketing & GTM" },
  { name: "Developer Marketing", category: "Marketing & GTM" },
  { name: "Category Creation", category: "Marketing & GTM" },
  { name: "Analyst Relations", category: "Marketing & GTM" },
  { name: "International Expansion", category: "Marketing & GTM" },
  { name: "Go-to-Market Planning", category: "Marketing & GTM" },
  { name: "Customer Segmentation", category: "Marketing & GTM" },
  { name: "Multi-Channel Marketing", category: "Marketing & GTM" },
  { name: "Brand Guidelines", category: "Marketing & GTM" },

  // ─── Product & Design (55) ──────────────────────────────────────────
  { name: "Product Strategy", category: "Product & Design" },
  { name: "Roadmapping", category: "Product & Design" },
  { name: "User Research", category: "Product & Design" },
  { name: "Wireframing", category: "Product & Design" },
  { name: "A/B Testing", category: "Product & Design" },
  { name: "Product Analytics", category: "Product & Design" },
  { name: "Customer Discovery", category: "Product & Design" },
  { name: "Sprint Planning", category: "Product & Design" },
  { name: "Product Stakeholder Management", category: "Product & Design" },
  { name: "Feature Prioritization", category: "Product & Design" },
  { name: "User Story Writing", category: "Product & Design" },
  { name: "Jobs to Be Done", category: "Product & Design" },
  { name: "Product-Market Fit", category: "Product & Design" },
  { name: "Prototyping", category: "Product & Design" },
  { name: "UX Design", category: "Product & Design" },
  { name: "UI Design", category: "Product & Design" },
  { name: "Design Systems", category: "Product & Design" },
  { name: "Interaction Design", category: "Product & Design" },
  { name: "Information Architecture", category: "Product & Design" },
  { name: "Usability Testing", category: "Product & Design" },
  { name: "Accessibility Design", category: "Product & Design" },
  { name: "Mobile Design", category: "Product & Design" },
  { name: "Responsive Design", category: "Product & Design" },
  { name: "Design Thinking", category: "Product & Design" },
  { name: "Visual Design", category: "Product & Design" },
  { name: "Motion Design", category: "Product & Design" },
  { name: "Figma", category: "Product & Design" },
  { name: "Product Requirements", category: "Product & Design" },
  { name: "Agile Methodology", category: "Product & Design" },
  { name: "Scrum", category: "Product & Design" },
  { name: "Kanban", category: "Product & Design" },
  { name: "Product Ops", category: "Product & Design" },
  { name: "Release Management", category: "Product & Design" },
  { name: "Beta Programs", category: "Product & Design" },
  { name: "Feature Flagging", category: "Product & Design" },
  { name: "Product Launches", category: "Product & Design" },
  { name: "Competitive Intelligence", category: "Product & Design" },
  { name: "Platform Strategy", category: "Product & Design" },
  { name: "API Design", category: "Product & Design" },
  { name: "Marketplace Design", category: "Product & Design" },
  { name: "Onboarding Design", category: "Product & Design" },
  { name: "Retention Analysis", category: "Product & Design" },
  { name: "Growth Experimentation", category: "Product & Design" },
  { name: "Customer Journey Mapping", category: "Product & Design" },
  { name: "Service Design", category: "Product & Design" },
  { name: "Voice of Customer", category: "Product & Design" },
  { name: "Product Vision", category: "Product & Design" },
  { name: "Technical Product Management", category: "Product & Design" },
  { name: "Cross-Platform Design", category: "Product & Design" },
  { name: "Design Research", category: "Product & Design" },
  { name: "Persona Development", category: "Product & Design" },
  { name: "Workshop Facilitation", category: "Product & Design" },
  { name: "Storyboarding", category: "Product & Design" },
  { name: "Design Critiques", category: "Product & Design" },
  { name: "Product Metrics", category: "Product & Design" },

  // ─── Engineering & Technical (55) ───────────────────────────────────
  { name: "APIs", category: "Engineering & Technical" },
  { name: "Prompt Engineering", category: "Engineering & Technical" },
  { name: "AI/ML", category: "Engineering & Technical" },
  { name: "Web Development", category: "Engineering & Technical" },
  { name: "Data Engineering", category: "Engineering & Technical" },
  { name: "System Architecture", category: "Engineering & Technical" },
  { name: "Cloud Infrastructure", category: "Engineering & Technical" },
  { name: "DevOps", category: "Engineering & Technical" },
  { name: "CI/CD", category: "Engineering & Technical" },
  { name: "Microservices", category: "Engineering & Technical" },
  { name: "Backend Development", category: "Engineering & Technical" },
  { name: "Frontend Development", category: "Engineering & Technical" },
  { name: "React", category: "Engineering & Technical" },
  { name: "TypeScript", category: "Engineering & Technical" },
  { name: "Node.js", category: "Engineering & Technical" },
  { name: "Python", category: "Engineering & Technical" },
  { name: "SQL", category: "Engineering & Technical" },
  { name: "PostgreSQL", category: "Engineering & Technical" },
  { name: "AWS", category: "Engineering & Technical" },
  { name: "GCP", category: "Engineering & Technical" },
  { name: "Azure", category: "Engineering & Technical" },
  { name: "Docker", category: "Engineering & Technical" },
  { name: "Kubernetes", category: "Engineering & Technical" },
  { name: "Security Engineering", category: "Engineering & Technical" },
  { name: "Performance Optimization", category: "Engineering & Technical" },
  { name: "Database Design", category: "Engineering & Technical" },
  { name: "Technical Architecture", category: "Engineering & Technical" },
  { name: "Code Review", category: "Engineering & Technical" },
  { name: "Technical Debt Management", category: "Engineering & Technical" },
  { name: "Engineering Management", category: "Engineering & Technical" },
  { name: "Technical Roadmapping", category: "Engineering & Technical" },
  { name: "Mobile Development", category: "Engineering & Technical" },
  { name: "iOS Development", category: "Engineering & Technical" },
  { name: "Android Development", category: "Engineering & Technical" },
  { name: "GraphQL", category: "Engineering & Technical" },
  { name: "REST API Design", category: "Engineering & Technical" },
  { name: "Machine Learning", category: "Engineering & Technical" },
  { name: "Natural Language Processing", category: "Engineering & Technical" },
  { name: "Computer Vision", category: "Engineering & Technical" },
  { name: "LLM Integration", category: "Engineering & Technical" },
  { name: "RAG Systems", category: "Engineering & Technical" },
  { name: "AI Agent Development", category: "Engineering & Technical" },
  { name: "Serverless Architecture", category: "Engineering & Technical" },
  { name: "Event-Driven Architecture", category: "Engineering & Technical" },
  { name: "Testing & QA", category: "Engineering & Technical" },
  { name: "Automated Testing", category: "Engineering & Technical" },
  { name: "Infrastructure as Code", category: "Engineering & Technical" },
  { name: "Terraform", category: "Engineering & Technical" },
  { name: "Observability", category: "Engineering & Technical" },
  { name: "Incident Management", category: "Engineering & Technical" },
  { name: "SRE", category: "Engineering & Technical" },
  { name: "Technical Writing", category: "Engineering & Technical" },
  { name: "Open Source", category: "Engineering & Technical" },
  { name: "Blockchain", category: "Engineering & Technical" },
  { name: "Full-Stack Development", category: "Engineering & Technical" },

  // ─── Finance & Operations (45) ──────────────────────────────────────
  { name: "Financial Modeling", category: "Finance & Operations" },
  { name: "Fundraising", category: "Finance & Operations" },
  { name: "P&L Management", category: "Finance & Operations" },
  { name: "Operations Management", category: "Finance & Operations" },
  { name: "Process Design", category: "Finance & Operations" },
  { name: "Vendor Management", category: "Finance & Operations" },
  { name: "Budget Management", category: "Finance & Operations" },
  { name: "Revenue Operations", category: "Finance & Operations" },
  { name: "Supply Chain Management", category: "Finance & Operations" },
  { name: "Procurement", category: "Finance & Operations" },
  { name: "Contract Negotiation", category: "Finance & Operations" },
  { name: "Legal Operations", category: "Finance & Operations" },
  { name: "Compliance", category: "Finance & Operations" },
  { name: "Risk Management", category: "Finance & Operations" },
  { name: "Forecasting", category: "Finance & Operations" },
  { name: "Unit Economics", category: "Finance & Operations" },
  { name: "Cash Flow Management", category: "Finance & Operations" },
  { name: "Cap Table Management", category: "Finance & Operations" },
  { name: "Due Diligence", category: "Finance & Operations" },
  { name: "Investor Reporting", category: "Finance & Operations" },
  { name: "SaaS Metrics", category: "Finance & Operations" },
  { name: "Revenue Recognition", category: "Finance & Operations" },
  { name: "Tax Strategy", category: "Finance & Operations" },
  { name: "Accounts Payable/Receivable", category: "Finance & Operations" },
  { name: "Payroll Management", category: "Finance & Operations" },
  { name: "Business Process Optimization", category: "Finance & Operations" },
  { name: "Lean Operations", category: "Finance & Operations" },
  { name: "Six Sigma", category: "Finance & Operations" },
  { name: "Project Management", category: "Finance & Operations" },
  { name: "Program Management", category: "Finance & Operations" },
  { name: "Resource Allocation", category: "Finance & Operations" },
  { name: "Capacity Planning", category: "Finance & Operations" },
  { name: "Quality Assurance", category: "Finance & Operations" },
  { name: "SOC 2 Compliance", category: "Finance & Operations" },
  { name: "GDPR Compliance", category: "Finance & Operations" },
  { name: "IPO Readiness", category: "Finance & Operations" },
  { name: "M&A Due Diligence", category: "Finance & Operations" },
  { name: "Business Continuity", category: "Finance & Operations" },
  { name: "FP&A", category: "Finance & Operations" },
  { name: "Strategic Finance", category: "Finance & Operations" },
  { name: "Scenario Planning", category: "Finance & Operations" },
  { name: "Cost Optimization", category: "Finance & Operations" },
  { name: "Billing Operations", category: "Finance & Operations" },
  { name: "Customer Success Operations", category: "Finance & Operations" },
  { name: "Logistics", category: "Finance & Operations" },

  // ─── Data & Analytics (45) ──────────────────────────────────────────
  { name: "Data Analysis", category: "Data & Analytics" },
  { name: "Business Intelligence", category: "Data & Analytics" },
  { name: "Experimentation", category: "Data & Analytics" },
  { name: "Attribution Modeling", category: "Data & Analytics" },
  { name: "Data Visualization", category: "Data & Analytics" },
  { name: "Statistical Analysis", category: "Data & Analytics" },
  { name: "Predictive Modeling", category: "Data & Analytics" },
  { name: "Data Strategy", category: "Data & Analytics" },
  { name: "Data Governance", category: "Data & Analytics" },
  { name: "ETL Pipelines", category: "Data & Analytics" },
  { name: "Data Warehousing", category: "Data & Analytics" },
  { name: "Tableau", category: "Data & Analytics" },
  { name: "Looker", category: "Data & Analytics" },
  { name: "Power BI", category: "Data & Analytics" },
  { name: "Google Analytics", category: "Data & Analytics" },
  { name: "Mixpanel", category: "Data & Analytics" },
  { name: "Amplitude", category: "Data & Analytics" },
  { name: "dbt", category: "Data & Analytics" },
  { name: "Snowflake", category: "Data & Analytics" },
  { name: "BigQuery", category: "Data & Analytics" },
  { name: "Databricks", category: "Data & Analytics" },
  { name: "Cohort Analysis", category: "Data & Analytics" },
  { name: "Funnel Analysis", category: "Data & Analytics" },
  { name: "Customer Analytics", category: "Data & Analytics" },
  { name: "Revenue Analytics", category: "Data & Analytics" },
  { name: "Web Analytics", category: "Data & Analytics" },
  { name: "Product Analytics", category: "Data & Analytics" },
  { name: "Marketing Analytics", category: "Data & Analytics" },
  { name: "Data Modeling", category: "Data & Analytics" },
  { name: "Regression Analysis", category: "Data & Analytics" },
  { name: "Hypothesis Testing", category: "Data & Analytics" },
  { name: "A/B Test Analysis", category: "Data & Analytics" },
  { name: "Data Storytelling", category: "Data & Analytics" },
  { name: "Dashboard Design", category: "Data & Analytics" },
  { name: "KPI Frameworks", category: "Data & Analytics" },
  { name: "Customer Lifetime Value", category: "Data & Analytics" },
  { name: "Churn Analysis", category: "Data & Analytics" },
  { name: "Segmentation Analysis", category: "Data & Analytics" },
  { name: "Multi-Touch Attribution", category: "Data & Analytics" },
  { name: "Data Quality Management", category: "Data & Analytics" },
  { name: "R", category: "Data & Analytics" },
  { name: "Pandas", category: "Data & Analytics" },
  { name: "Jupyter Notebooks", category: "Data & Analytics" },
  { name: "Monte Carlo Simulation", category: "Data & Analytics" },
  { name: "Causal Inference", category: "Data & Analytics" },

  // ─── Creative (42) ──────────────────────────────────────────────────
  { name: "Copywriting", category: "Creative" },
  { name: "Art Direction", category: "Creative" },
  { name: "Video Production", category: "Creative" },
  { name: "Graphic Design", category: "Creative" },
  { name: "Brand Identity", category: "Creative" },
  { name: "Photography", category: "Creative" },
  { name: "Illustration", category: "Creative" },
  { name: "Typography", category: "Creative" },
  { name: "Creative Direction", category: "Creative" },
  { name: "Storytelling", category: "Creative" },
  { name: "Content Creation", category: "Creative" },
  { name: "Social Media Content", category: "Creative" },
  { name: "Video Editing", category: "Creative" },
  { name: "Motion Graphics", category: "Creative" },
  { name: "Animation", category: "Creative" },
  { name: "Podcast Production", category: "Creative" },
  { name: "Audio Production", category: "Creative" },
  { name: "UX Writing", category: "Creative" },
  { name: "Editorial Strategy", category: "Creative" },
  { name: "Brand Voice", category: "Creative" },
  { name: "Tone of Voice", category: "Creative" },
  { name: "Visual Storytelling", category: "Creative" },
  { name: "Presentation Design", category: "Creative" },
  { name: "Pitch Deck Design", category: "Creative" },
  { name: "Packaging Design", category: "Creative" },
  { name: "Print Design", category: "Creative" },
  { name: "Web Design", category: "Creative" },
  { name: "Email Design", category: "Creative" },
  { name: "Ad Creative", category: "Creative" },
  { name: "Campaign Creative", category: "Creative" },
  { name: "Scriptwriting", category: "Creative" },
  { name: "Blog Writing", category: "Creative" },
  { name: "Ghostwriting", category: "Creative" },
  { name: "Editing & Proofreading", category: "Creative" },
  { name: "3D Design", category: "Creative" },
  { name: "Color Theory", category: "Creative" },
  { name: "Layout Design", category: "Creative" },
  { name: "Icon Design", category: "Creative" },
  { name: "Infographic Design", category: "Creative" },
  { name: "Creative Strategy", category: "Creative" },
  { name: "Naming & Nomenclature", category: "Creative" },
  { name: "Storyboarding", category: "Creative" },

  // ─── Other (40) ─────────────────────────────────────────────────────
  { name: "Customer Success", category: "Other" },
  { name: "Account Management", category: "Other" },
  { name: "Sales", category: "Other" },
  { name: "Enterprise Sales", category: "Other" },
  { name: "Solution Engineering", category: "Other" },
  { name: "Customer Onboarding", category: "Other" },
  { name: "Technical Support", category: "Other" },
  { name: "Customer Experience", category: "Other" },
  { name: "Consulting", category: "Other" },
  { name: "Business Development", category: "Other" },
  { name: "Partnerships", category: "Other" },
  { name: "Strategic Alliances", category: "Other" },
  { name: "Real Estate", category: "Other" },
  { name: "Healthcare", category: "Other" },
  { name: "EdTech", category: "Other" },
  { name: "FinTech", category: "Other" },
  { name: "E-Commerce", category: "Other" },
  { name: "Marketplace Operations", category: "Other" },
  { name: "Government Relations", category: "Other" },
  { name: "Policy Development", category: "Other" },
  { name: "Sustainability", category: "Other" },
  { name: "Corporate Social Responsibility", category: "Other" },
  { name: "Nonprofit Management", category: "Other" },
  { name: "Board Governance", category: "Other" },
  { name: "Franchise Development", category: "Other" },
  { name: "International Business", category: "Other" },
  { name: "Localization", category: "Other" },
  { name: "User Training", category: "Other" },
  { name: "Knowledge Management", category: "Other" },
  { name: "Documentation", category: "Other" },
  { name: "Startup Advisory", category: "Other" },
  { name: "Angel Investing", category: "Other" },
  { name: "Venture Capital", category: "Other" },
  { name: "Product-Led Sales", category: "Other" },
  { name: "Self-Serve Revenue", category: "Other" },
  { name: "Customer Retention", category: "Other" },
  { name: "Churn Reduction", category: "Other" },
  { name: "Net Revenue Retention", category: "Other" },
  { name: "Industry Analysis", category: "Other" },
  { name: "Trend Forecasting", category: "Other" },
];
